// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI3F72lemoCAbE-33_tRTrVBn8mY_pubQ',
    appId: '1:412567521069:web:315e9303eb86106ea2b5a4',
    messagingSenderId: '412567521069',
    projectId: 'real-time-tracking-f90b5',
    authDomain: 'real-time-tracking-f90b5.firebaseapp.com',
    storageBucket: 'real-time-tracking-f90b5.firebasestorage.app',
    measurementId: 'G-N0NF966ZVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNlHI30Nl8zW4MORslgqiHu_DPNER3XQQ',
    appId: '1:412567521069:android:4144cf27b036df14a2b5a4',
    messagingSenderId: '412567521069',
    projectId: 'real-time-tracking-f90b5',
    storageBucket: 'real-time-tracking-f90b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb-Lx7j5MkgS2DVyFhAB6GEmVNA0h0ZvU',
    appId: '1:412567521069:ios:26fd4c08b4762f7aa2b5a4',
    messagingSenderId: '412567521069',
    projectId: 'real-time-tracking-f90b5',
    storageBucket: 'real-time-tracking-f90b5.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb-Lx7j5MkgS2DVyFhAB6GEmVNA0h0ZvU',
    appId: '1:412567521069:ios:26fd4c08b4762f7aa2b5a4',
    messagingSenderId: '412567521069',
    projectId: 'real-time-tracking-f90b5',
    storageBucket: 'real-time-tracking-f90b5.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI3F72lemoCAbE-33_tRTrVBn8mY_pubQ',
    appId: '1:412567521069:web:cf3224d261fff747a2b5a4',
    messagingSenderId: '412567521069',
    projectId: 'real-time-tracking-f90b5',
    authDomain: 'real-time-tracking-f90b5.firebaseapp.com',
    storageBucket: 'real-time-tracking-f90b5.firebasestorage.app',
    measurementId: 'G-1RPLSPVH0K',
  );
}
